### ISSUE TITLE
No public token callback if user does not click Finish Setup

### ISSUE THREAD

**Issue by marcel** [merge-api/react-merge-link#21]
We've identified a UX failure mode where a customer will successfully authenticate with some integration but they do not click on the `Finish Setup` button at the bottom of the modal. Perhaps they just quickly scan the `Successfully set up your integration!` text and click away from the modal, or close the tab or what have you, because they think they are done. In a perfect world we'd expect everyone to see and click on that button, but if they don't it's a rather problematic failure mode for us. 

If that button is not clicked the public token callback isn't fired. If it isn't fired we have neither the public token or a means to exchange it for an account token. But from the perspective of merge, the account is linked and its status is complete.

Production account tokens are no longer accessible on the merge admin website. They are only available via the API. But in order to make the API request you need the public token. We have neither.

A potential solution is to trigger the callback as soon as you have a public token available and add some other callback akin to the onExit one, or just overload that one to be triggered both by the X in the top right or the finish setup button, for those who care about the Finish Setup button being pressed and the modal dismissed. But if the public token is already generated once the Finish Setup button please just give it to us without requiring that they click the button.

**Comment by eltonkl** [comment]
Hi @marcel, this should be fixed via #23, which is published in https://www.npmjs.com/package/@mergeapi/react-merge-link/v/2.0.0.

**Comment by marcel** [comment]
Works like a charm. Thank you so much!
