### ISSUE TITLE
Modal can't be closed by keyboard alone

### ISSUE THREAD

**Issue by jshakes** [merge-api/react-merge-link#34]
Apologies in advance if this isn't the right repo for this issue.

The Merge Link modal can't be closed without clicking/tapping the close button, which means the modal is broken for keyboard/AT users.

To fix this:
- The close button should be written with the `<button>` tag so it is focusable
- Pressing the escape key should close the modal
 
![Screen Shot 2023-01-04 at 10 08 23 AM](https://user-images.githubusercontent.com/591884/210531857-39469f96-7c81-4831-ba83-2b5d35ee5c90.png)

It is also considered good practice to auto-focus the close button once the modal opens so that keyboard/AT users can start interacting with the modal's contents.

**Comment by hmafzal** [comment]
Hello, thank you for the feedback! This is now fixed.
