### ISSUE TITLE
Browsers block popup when you connect hr system

### ISSUE THREAD

**Issue by avasylchuk** [merge-api/react-merge-link#43]
Hello!

Most browsers try to block popup when I want to connect an HR system (BambooHR in this case) through BambooHR's website.
When i choose this option I see an error message about blocking popup and new popup is not opened till I allow it in browser's settings.

It looks like there is an approach to fix it by emulating user's click event.
Here is details https://javascript.info/popup-windows#popup-blocking

Could you look at this and try to apply?

**Comment by hmafzal** [comment]
Hello, thanks for reporting this! This should be fixed in more recent versions, please let us know if you are still encountering this.
