### ISSUE TITLE
Body styles are not always restored

### ISSUE THREAD

**Issue by jaycle** [merge-api/react-merge-link#46]
When using this hook, the script pulled in at https://cdn.merge.dev/initialize.js appears to attempt to restore the body styles upon exit, though it is hard to tell since the source is minified.

When calling `open()` and then selecting an integration, if the modal is closed then the `body.style` keeps the `overflow: hidden` attribute. This has the effect of breaking scroll on our site until refresh.

**Comment by jaycle** [comment]
Upon further inspection, it seems that our code was calling `open()` twice, due to some re-render effects. We can protect against that, though it may be nice if the hook/library protected against a double initialization/call to open.

**Comment by chestozo** [comment]
+1 we are facing the same issue now
Calling `open()` for a 2nd time stores wrong styles on body and after closing Merge popup - restores those wrong styles and break scroll in the whole app.

**Comment by ankitd33** [comment]
Closing as this should be fixed now! Let me know if it isnt
