### ISSUE TITLE
No dist folder found in node_modules 2.0.7

### ISSUE THREAD

**Issue by sjkcodes** [merge-api/react-merge-link#48]
I'm consistently getting

```Cannot find module '@mergeapi/react-merge-link' or its corresponding type declarations.ts(2307)```

from my import, though it is definitely installed, shows up in package, package-lock, node_modules

```import { useMergeLink } from "@mergeapi/react-merge-link"```

Additional info:

In package.json for ```@mergeapi/react-merge-link``` I see   ```"main": "dist/index.umd.js",```, but there is no dist folder in  ```node_modules/@mergeapi/react-merge-link```

Looks like you guys forgot to transpile this version, I see dist is in 2.0.6

**Comment by triveni692** [comment]
I am facing this issue as well when I try to import in my Next.js project. I'm using version 2.0.7 as well.

**Comment by ankitd33** [comment]
Ah just published another version that should fix this - 2.1.1 should have the dist folder included!

**Comment by triveni692** [comment]
The new version did fix the issue for me.
