### ISSUE TITLE
No CHANGELOG or Release Notes

### ISSUE THREAD

**Issue by judson-stevens-teampay** [merge-api/react-merge-link#51]
Please let me know if I'm missing something - there doesn't seem to be any release notes or a CHANGELOG to reference with version upgrades which means we're having to read commit diffs to attempt to determine what changes have been made. Since there doesn't seem to be any tagging either (again please tell me if I'm missing it!), it's essentially a bit of guesswork to determine what commits are part of what release. I guess we could take the code downloads from `npm` and do a diff there? 

Anyway, if I'm missing something I'm happy to be corrected; we'd love to have some documentation about what's going into each release so we aren't just upgrading blindly.

**Comment by hmafzal** [comment]
Good call out @judson-stevens-teampay! We'll start including release notes and a changelog for future releases.

**Comment by judson-stevens-teampay** [comment]
Great, thank you!
