### ISSUE TITLE
How can we disable mappings (map custom fields) in merge link dialog

### ISSUE THREAD

**Issue by StephaneBischoffVasco** [merge-api/react-merge-link#55]
How can we disable mappings (map custom fields) in merge link dialog.

<img src="https://github.com/merge-api/react-merge-link/assets/160048082/770e5980-f403-41eb-a964-6c123f5c14bd" width="300">
<img src="https://github.com/merge-api/react-merge-link/assets/160048082/fdf304eb-1829-4f2f-a8aa-0df4704574e1" width="300">

**Comment by hmafzal** [comment]
@StephaneBischoffVasco you can find that in our docs here: https://docs.merge.dev/supplemental-data/field-mappings/create-field-mapping/for-linked-account/

You must turn off the "Mappable in Link" option for your target fields in your dashboard.
